# -*- coding: utf-8 -*-
"""Berkom lagi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FeYtB3vkDCs4OjB_eeWTTVwKx4osxRK9
"""



def langkah_bolu_kukus () :
    print ("====LANGKAH MEMASAK====")
    langkah_1 = [ "Siapkan 6 sdm tepung terigu, 2 butir telur ayam, 6 sdm gula pasir, 8 sdm air hangat, 8 sdm minyak goreng, 2 sdm susu bubuk, 1 sdt baking powder, 40 gram keju parut",
"Kocok telur dan gula pasir hingga berbusa dan beri air hangat",
"Masukkan tepung terigu,susu bubuk dan baking powder,aduk hingga tercampur rata lalu saring adonan"]
    for i, item in enumerate(langkah_1, start=1):
        print(f"{i}. {item}")

    Nanya= input("Apakah sampai disini masih aman atau gagal? (aman/gagal): ").strip().lower()
    if Nanya == "aman":
        langkah_2 = ["Masukkan keju parut,aduk rata kemudian masukkan minyak goreng, aduk hingga tercampur rata",
"Siapkan loyang, lalu olesi dgn margarin tipis-tipis. Kemudian tuang adonan ke loyang",
"Masukkan loyang ke dalam rice cooker. Nyalakan rice cooker. Tunggu hingga matang.",
"Keluarkan loyang dari rice cooker jika sudah matang. Bolu kukus siap disantap."]
        for i, item in enumerate(langkah_2, start=4):
            print(f"{i}. {item}")
    elif Nanya == "gagal":
        print ("Coba Cek bahan")
        langkah_bolu_kukus ()
    print ("===SELESAI===")

def langkah_Yogurt_Brownie ():
    print ("====LANGKAH MEMASAK====")
    langkah_1 = [ "Masukkan margarin cair, bubuk brownies instant, telur kocok, susu full cream ke dalam rice cooker",
"Aduk sampai rata", "Siapkan mangkuk, lalu masukkan yogurt, telur, gula pasir, dan tepung terigu ke dalamnya.",
"Aduk rata", "Masukkan ke dalam adonan brownies", "Aduk rata", "Tutup ricecooker"]
    for i, item in enumerate(langkah_1, start=1):
        print(f"{i}. {item}")
    while True :
        Nanya= input("Apakah sudah siap/matang? (sudah/belum): ").strip().lower()
        if Nanya == "sudah":
            break
        else:
            print ("Ulangi langkah sebelumnya.")

    langkah_2 = ["Nyalakan tombol “Cooking” dan tunggu sampai otomatis berpindah ke bagian “Magic Warmer”",
    "Setelah matang, buka rice cooker dan tunggu 10 menit.", "Keluarkan dari wadah rice cooker." "Brownies siap difoto dan disantap"]
    for i, item in enumerate(langkah_2, start=8):
        print(f"{i}. {item}")
    print ("===SELESAI===")

def langkah_French_Toast () :
    print ("====LANGKAH MEMASAK====")
    langkah_1 = [ "Campurkan telur dan susu jadi satu. Aduk hingga tercampur rata.",
"Celupkan roti tawar. Bolak balik agar rata",
"Panggang menggunakan teflon yang sudah diolesi margarine. Bolak balik hingga kecoklatan. Pastikan kedua sisi matang merata",
"Sajikan dengan topping kesukaan. Bisa ice cream, granola, buah-buahan, atau madu."]
    print ("===SELESAI===")

def langkah_Lekker ():
    print ("====LANGKAH MEMASAK====")
    langkah_1 = [" Masukkan tepung beras, tepung terigu, gula pasir, baking powder, garam, dan telur.",
"Aduk hingga semua bahan tercampur rata"]
    for i, item in enumerate(langkah_1, start=1):
        print(f"{i}. {item}")
        Nanya= input("Apakah sampai disini masih aman atau gagal? (aman/gagal): ").strip().lower()
        if Nanya == "aman":
            langkah_2 = ["Nyalakan kompor api sedang", "Siapkan teflon", "Oleskan margarin sedikit di dalam teflon",
                 "Tuang adonan ke dalam teflon secukupnya", "Tambahkan topping sesuai selera",
                 "Tunggu sekitar 30 detik, lalu lipat adonan lekker","Angkat dari teflon",
                 "Terus ulangi sampai adonan lekker habis"]
            for i, item in enumerate(langkah_2, start=3):
                print(f"{i}. {item}")
        else:
            print ("Cek kembali adonan")
            langkah_Lekker()

    print ("===SELESAI===")

def langkah_bubur_kacang_ijo ():
    print ("====LANGKAH MEMASAK====")
    langkah_1 = [ "Cuci bersih kacang ijo, rebus secukupnya air sampe mendidih masukkan garam, daun pandan dan kacang ijo. Tunggu air mendidih lagi kurleb 5 menit kemudian matikan api (tutup pancinya). Diamkan minim 30 menit",
"Setelah 30 menit (minimal) terjadi proses pematangannya jd airnya di serap kacang ijonya."]
    for i, item in enumerate(langkah_1, start=1):
        print(f"{i}. {item}")
    while True :
        Nanya= input("Apakah sampai disini masih aman atau gagal? (aman/gagal): ").strip().lower()
        if Nanya == "aman":
            break
        else:
            print ("Masak selama 10 menit.")

    langkah_2 = ["Setelah itu masak lagi sekitar 7-10 menit. Terakhir masukkan santan dan gula di awal aduk agar santan tdk pecah masak sampe empuk dan kacang ijo bermekaran koreksi rasanya dan matikan api. Banyaknya air sesuaikan.",
"Tunggu hangat siap di hidangkan (hangat/dingin sama enaknya)"]
    for i, item in enumerate(langkah_2, start=3):
        print(f"{i}. {item}")
    print ("===SELESAI===")

def langkah_kue_coklat():
    print ("====LANGKAH MEMASAK====")
    langkah_1 = ["Masukkan semua bahan ke dalam panci", "Aduk hingga merata", "Nyalakan kompor api kecil",
"Segera tutup panci dengan penutupnya", "Tunggu hingga matang",
"Kamu bisa coba menusuk adonan kue coklat dengan tusuk sate untuk mengetes kematangannya",
"Jika sudah tidak ada adonan yang menempel pada tusuk sate, artinya kue coklat sudah matang", "Angkat dari panci dan sajikan."]
    for i, item in enumerate(langkah_1, start=1):
        print(f"{i}. {item}")

    print ("===SELESAI===")

#Langkah asin
def langkah_nasi_goreng ():
    print ("====LANGKAH MEMASAK====")
    langkah_1 = [ "Siapkan 100gr beras, 700mL air, 70gr dada ayam, 5 siung bawang putih, 5 siung bawang merah, 1 batang daun bawang, 1 buah wortel, 5 buah buncis, 1 sdm saus tomat, ½ sdm kecap manis, 1 sdt lada hitam, 1 sdt garam",
"Masukkan minyak dan bawang",
"Aduk hingga layu", "Masukkan wortel, buncis, ayam, beras, saus tomat, dan kecap",
"Masukkan air mineral hingga 1 ruas jari diatas permukaan beras",
"Tutup dan nyalakan mode cook selama 30 menit (aduk beberapa menit sekali)",
"Nasi goreng siap disantap"]
    for i, item in enumerate(langkah_1, start=1):
        print(f"{i}. {item}")
    print ("===SELESAI===")

def langkah_mac_and_cheese():
    print ("====LANGKAH MEMASAK====")
    langkah_1 = [ "Masukkan semua bahan lalu aduk", "Masak di ricecooker sekitar 10 menit", "Buka tutup ricecooker",
                 "Tambahkan keju sesuai selera",
                 "Kamu juga bisa menambahkan topping lainnya jika mau, seperti sosis, smoked beef, dll.",
"Tutup ricecooker dan nyalakan mode masak, tunggu sekitar 1 menit.",
"Buka kembali tutup ricecooker",
"Mac & Cheese siap disantap"]
    for i, item in enumerate(langkah_1, start=1):
        print(f"{i}. {item}")
    print ("===SELESAI===")

def langkah_tumis_jamur_sosis():
    print ("====LANGKAH MEMASAK====")
    langkah_1 = [ "Siapkan 1 bungkus jamur tiram, 2 sdm saori saus tiram, 1 sosis, 2 cabe merah, 1 sdm kecap manis, 2 sdm minyak, 1 jumput garam, 1 royco secukupnya, 1 siung bawang merah, dan 1 siung bawang putih",
"Cuci bersih jamur, lalu suir suir.", "Cincang sosis, bawang merah, bawang putih, dan cabai",
"Masukkan minyak. Tumis sosis, bawang merah, bawang putih, dan cabai hingga harum", "Masukkan jamur.",
"Tambahkan garam, saus tiram, dan kecap secukupnya", "Tumis hingga jamur berair dan tunggu sampai menyusut"
"Tumis jamur sosis siap disantap"]
    for i, item in enumerate(langkah_1, start=1):
        print(f"{i}. {item}")
    print ("===SELESAI===")

def langkah_ayam_goreng_lada_putih():
    print ("====LANGKAH MEMASAK====")
    langkah_1 = ["Siapkan 250gr ayam fillet, jeruk nipis, 2 butir bawang putih, ketumbar bubuk, minyak goreng, dan lada putih bubuk",
"Baluri ayam fillet dengan jeruk nipis, ketumbar, dan lada putih. Biarkan selama 15 menit."]
    for i, item in enumerate(langkah_1, start=1):
        print(f"{i}. {item}")

    Nanya= input("Apakah sampai disini masih aman atau gagal? (aman/gagal): ").strip().lower()
    if Nanya == "aman":
        langkah_2 = ["Panaskan minyak diatas teflon dan masukkan ayam ke dalam minyak panas.",
"Angkat dan tiriskan ayam. Ayam siap dihidangkan."]
        for i, item in enumerate(langkah_2, start=3):
            print(f"{i}. {item}")
    elif Nanya == "gagal":
        print ("Diamkan ayam fillet selama 5 menit. Lanjut step 3")
        langkah_2 = ["Panaskan minyak diatas teflon dan masukkan ayam ke dalam minyak panas.",
"Angkat dan tiriskan ayam. Ayam siap dihidangkan."]
        for i, item in enumerate(langkah_2, start=3):
            print(f"{i}. {item}")
    print ("===SELESAI===")

def langkah_sop ():
    print ("====LANGKAH MEMASAK====")
    langkah_1 = ["Siapkan 1 buah wortel ukuran sedang, ,1 buah kentang, 1 bonggol kol ukuran kecil, 1 batang daun bawang, 1 batang seledri, 1 siung bawang putih, 1 liter air, garam, gula, Lada, dan Kaldu bubuk/penyedap rasa",
"Cuci dan potong wortel, kentang, kol, daun bawang, dan seledri", "Ulek bawang putih", "Siapkan panci untuk memasak",
"tuangkan sedikit minyak", "panaskan dan tumis bawang putih sampai harum", "Setelah harum, masukkan air kemudian kentang"]
    for i, item in enumerate(langkah_1, start=1):
        print(f"{i}. {item}")
    while True :
        Nanya= input("Apakah sudah siap/matang? (sudah/belum): ").strip().lower()
        if Nanya == "sudah":
            break
        else:
            print ("Tutup panci dan tunggu hingga kentang lunak.")

    langkah_2 = ["Setelah kentang dirasa mulai empuk, masukkan wortel", "Setelah wortel mulai empuk juga, masukkan kol",
"Tambahkan garam, gula, dan lada secukupnya", "masukkan daun bawang dan seledri yang sudah dipotong-potong juga biar sop-mu tambah terlihat segar dan juga harum"]
    for i, item in enumerate(langkah_2, start=8):
        print(f"{i}. {item}")
    print ("===SELESAI===")

def langkah_nasi_panda ():
    print ("====LANGKAH MEMASAK====")
    langkah_1 = ["siapkan panci dan letakkan di atas kompor", "masukan minyak ke dalam panci",
"nyalakan kompor sampai api sedang", "pecahkan telur dan masukkan ke dalam panci",
"masak telur hingga matang sesuai selera",
"matikan api jika telur sudah matang, dan angkat telur dari panci, lalu taruh di piring",
"siapkan cabe merah, cabe hijau, cabe rawit, daun bawang dan potong sesuai ukuran yang diingikan (usahakan agar jangan terlalu besar maupun terlalu kecil)",
"masukkan bahan-bahan yang sudah dipotong ke dalam panci", "nyalakan kompor kembali sampai api sedang",
"tumis bahan-bahan di dalamnya","tambahkan bumbu penyedap", "tambahkan saus tiram cap panda", "tumis sampai bahan-bahannya layu",
"matikan kompor", "siapkan wadah, masukkan nasi ke atas wadah",
"taruh telur di atas nasi", "tambahkan bumbu yang telah dimasak di dalam panci tadi", "nasi panda siap disantap"]
    for i, item in enumerate(langkah_1, start=1):
        print(f"{i}. {item}")
    print ("===SELESAI===")




def utama ():
    import time
    print("Selamat datang di dapur anak kos")
    time.sleep(1)
    print("Silahkan pilih jenis makanan yang sesuai dengan mood kamu hari ini")
    time.sleep(1)

    jenis_resep = ["Manis","Asin"]
    for i, item in enumerate(jenis_resep, start=1):
        print(f"{i}. {item}")
    while True :
        hasil = int(input("Mau yang mana nih ? : "))
        if hasil == 2 :
            print("Pilih jenis alat yang kamu punya")
            jenis_alat = ["Rice Cooker","Teflon","Panci"]
            for i, item in enumerate(jenis_alat, start=1):
                print(f"{i}. {item}")
            while True :
                pilihan_alat = int(input("Mau yang mana nih ? : "))
                if pilihan_alat == 1 :
                    print("Resep makanan yang kamu mau")
                    jenis_resep = ["Nasi Goreng", "Mac and Cheese"]
                    for i, item in enumerate(jenis_resep, start=1):
                        print(f"{i}. {item}")
                    while True :
                        pilihan_resep = int(input("Mau yang mana nih ? : "))
                        if pilihan_resep == 1:
                            langkah_nasi_goreng ()
                            break
                        elif pilihan_resep == 2:
                            langkah_mac_and_cheese ()
                            break
                        else :
                            print("Masukkan angka yang valid")
                    break
                elif pilihan_alat == 2 :
                    print("Resep makanan yang kamu mau")
                    jenis_resep = ["Tumis Jamur Sosis", "Ayam Goreng Lada Putih"]
                    for i, item in enumerate(jenis_resep, start=1):
                        print(f"{i}. {item}")
                    while True :
                        pilihan_resep = int(input("Mau yang mana nih ? : "))
                        if pilihan_resep == 1:
                            langkah_tumis_jamur_sosis ()
                            break
                        elif pilihan_resep==2:
                            langkah_ayam_goreng_lada_putih ()
                            break
                        else:
                            print("Masukkan angka yang valid")
                    break
                elif pilihan_alat == 3 :
                    print("Resep makanan yang kamu mau")
                    jenis_resep = ["Sop", "Nasi Panda"]
                    for i, item in enumerate(jenis_resep, start=1):
                        print(f"{i}. {item}")
                    while True :
                        pilihan_resep = int(input("Mau yang mana nih ? : "))
                        if pilihan_resep == 1:
                            langkah_sop ()
                            break
                        elif pilihan_resep==2:
                            langkah_nasi_panda()
                            break
                        else :
                            print("Masukkan angka yang valid")
                    break
                else :
                    print ("Masukkan angka yang valid")

            break
        elif hasil == 1:
            print("Pilih jenis alat yang kamu punya")
            jenis_alat = ["Rice Cooker","Teflon","Panci"]
            for i, item in enumerate(jenis_alat, start=1):
                print(f"{i}. {item}")
            while True :
                pilihan_alat = int(input("Mau yang mana nih ? : "))
                if pilihan_alat == 1 :
                    print("Resep makanan yang kamu mau")
                    jenis_resep = ["Bolu Kukus", "Yogurt Brownies"]
                    for i, item in enumerate(jenis_resep, start=1):
                        print(f"{i}. {item}")
                    while True :
                        pilihan_resep = int(input("Mau yang mana nih ? : "))
                        if pilihan_resep == 1:
                            langkah_bolu_kukus ()
                            break
                        elif pilihan_resep == 2:
                            langkah_Yogurt_Brownie ()
                            break
                        else :
                            print ("Masukkan angka yang valid")
                    break
                elif pilihan_alat == 2 :
                    print("Resep makanan yang kamu mau")
                    jenis_resep = ["French Toast", "Lekker"]
                    for i, item in enumerate(jenis_resep, start=1):
                        print(f"{i}. {item}")
                    while True :
                        pilihan_resep = int(input("Mau yang mana nih ? : "))
                        if pilihan_resep == 1:
                            langkah_French_Toast ()
                            break
                        elif pilihan_resep== 2:
                            langkah_Lekker ()
                            break
                        else :
                            print ("Masukkan angka yang valid")
                    break
                elif pilihan_alat == 3 :
                    print("Resep makanan yang kamu mau")
                    jenis_resep = ["Bubur Kacang Ijo", "Kue Coklat"]
                    for i, item in enumerate(jenis_resep, start=1):
                        print(f"{i}. {item}")
                    while True :
                        pilihan_resep = int(input("Mau yang mana nih ? : "))
                        if pilihan_resep == 1:
                            langkah_bubur_kacang_ijo ()
                            break
                        elif pilihan_resep == 2:
                            langkah_kue_coklat()
                            break
                        else :
                            print ("Masukkan angka yang valid")
                    break
                else :
                    print ("Masukkan angka yang valid")
            break
        else:
            print ("Masukkan Angka yang valid")


utama ()